# -*- coding: utf-8 -*-
"""CODTECH TASK 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDBsOqepI1-qGzTsrXqd7X-3ZmlaZl-C
"""

!pip install transformers
!pip install datasets
!pip install torchaudio
!pip install jiwer
!pip install evaluate

from datasets import load_dataset
from transformers import pipeline
from jiwer import wer
import pandas as pd
import time

dataset = load_dataset(
    "hf-internal-testing/librispeech_asr_dummy",
    "clean",
    split="validation[:5]"
)

print(dataset)

print(dataset[0].keys())

asr = pipeline(
    "automatic-speech-recognition",
    model="facebook/wav2vec2-base-960h"
)

print("Model Loaded Successfully")

audio = dataset[0]["audio"]["array"]

prediction = asr(audio)

print("Predicted Text:")
print(prediction["text"])

print("\nActual Text:")
print(dataset[0]["text"])

reference = dataset[0]["text"]

predicted = prediction["text"]

error = wer(reference, predicted)

print("WER:", error)

results = []

for i in range(5):

    audio = dataset[i]["audio"]["array"]

    prediction = asr(audio)

    predicted_text = prediction["text"]

    actual_text = dataset[i]["text"]

    error = wer(actual_text, predicted_text)

    results.append(
        [i+1,
         actual_text,
         predicted_text,
         error]
    )

print("Done")

df = pd.DataFrame(
    results,
    columns=[
        "Sample",
        "Actual Text",
        "Predicted Text",
        "WER"
    ]
)

df

average_wer = df["WER"].mean()

print("Average WER:", average_wer)

whisper = pipeline(
    "automatic-speech-recognition",
    model="openai/whisper-small"
)

print("Whisper Loaded")

whisper_results = []

for i in range(5):

    audio = dataset[i]["audio"]["array"]

    prediction = whisper(audio)

    predicted_text = prediction["text"]

    actual_text = dataset[i]["text"]

    error = wer(actual_text, predicted_text)

    whisper_results.append(error)

print("Done")

whisper_avg_wer = sum(
    whisper_results
) / len(
    whisper_results
)

print("Whisper Average WER:", whisper_avg_wer)

start = time.time()

for i in range(5):

    audio = dataset[i]["audio"]["array"]

    asr(audio)

end = time.time()

wav2vec_time = end - start

print("Wav2Vec2 Time:", wav2vec_time)

start = time.time()

for i in range(5):

    audio = dataset[i]["audio"]["array"]

    whisper(audio)

end = time.time()

whisper_time = end - start

print("Whisper Time:", whisper_time)

comparison = pd.DataFrame({

    "Model":[
        "Wav2Vec2",
        "Whisper"
    ],

    "WER":[
        average_wer,
        whisper_avg_wer
    ],

    "Time":[
        wav2vec_time,
        whisper_time
    ]
})

comparison

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

plt.bar(
    comparison["Model"],
    comparison["WER"]
)

plt.title(
    "WER Comparison"
)

plt.ylabel(
    "WER"
)

plt.show()

!pip install noisereduce

import noisereduce as nr

audio = dataset[0]["audio"]["array"]

sample_rate = dataset[0]["audio"]["sampling_rate"]

clean_audio = nr.reduce_noise(
    y=audio,
    sr=sample_rate
)

print("Noise Reduced Successfully")

prediction = asr(clean_audio)

print(prediction["text"])

original_prediction = asr(audio)

clean_prediction = asr(clean_audio)

print("Original Audio:")
print(original_prediction["text"])

print("\nNoise Reduced Audio:")
print(clean_prediction["text"])

!pip install sounddevice
!pip install scipy

!apt-get install libportaudio2
import sounddevice as sd
from scipy.io.wavfile import write

from IPython.display import Javascript
from google.colab import output
from base64 import b64decode

RECORD = """
const sleep = time => new Promise(resolve => setTimeout(resolve, time))

async function record() {
  const stream = await navigator.mediaDevices.getUserMedia({audio:true});

  const recorder = new MediaRecorder(stream);
  const data = [];

  recorder.ondataavailable = event => data.push(event.data);

  recorder.start();

  await sleep(5000);

  recorder.stop();

  await new Promise(resolve => recorder.onstop = resolve);

  const audioBlob = new Blob(data, {type:'audio/wav'});
  const reader = new FileReader();

  reader.readAsDataURL(audioBlob);

  return await new Promise(resolve=>{
    reader.onloadend = ()=>resolve(reader.result);
  });
}
"""

display(Javascript(RECORD))

audio_string = output.eval_js("record()")

with open("recorded.wav","wb") as f:
    f.write(
        b64decode(
            audio_string.split(",")[1]
        )
    )

print("Recording Saved")

import librosa

audio, sr = librosa.load(
    "recorded.wav",
    sr=16000
)

prediction = asr(audio)

print(prediction["text"])

import librosa
import librosa.display
import matplotlib.pyplot as plt

audio, sr = librosa.load(
    "recorded.wav",
    sr=16000
)

plt.figure(figsize=(12,4))

librosa.display.waveshow(
    audio,
    sr=sr
)

plt.title("Audio Waveform")
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")

plt.show()

import noisereduce as nr
import librosa.display
import matplotlib.pyplot as plt

clean_audio = nr.reduce_noise(
    y=audio,
    sr=sr
)

plt.figure(figsize=(12,4))

librosa.display.waveshow(
    audio,
    sr=sr,
)

plt.title("Original Audio Waveform")

plt.show()

plt.figure(figsize=(12,4))

librosa.display.waveshow(
    clean_audio,
    sr=sr,
)

plt.title("Noise Reduced Audio Waveform")

plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    df["Sample"],
    df["WER"],
    marker='o'
)

plt.title("WER Across Audio Samples")
plt.xlabel("Audio Sample")
plt.ylabel("WER")

plt.grid(True)

plt.show()